<?php

namespace App\Utils\Constants;

class FixedValuesConstants
{
    const STATUS_DEMANDE_SOUMISE = "STATUS_DEMANDE_SOUMISE";
    const STATUS_DEMANDE_EN_COURS_TRAITEMENT = "STATUS_DEMANDE_EN_COURS_TRAITEMENT";
    const STATUS_DEMANDE_VALIDEE = "STATUS_DEMANDE_VALIDEE";
    const STATUS_DEMANDE_ANNULEE =  "STATUS_DEMANDE_ANNULEE";
    const STATUS_DEMANDE_REJETEE = "STATUS_DEMANDE_REJETEE";
}
